### ISSUE TITLE
Предложение по max-width

### ISSUE THREAD

**Issue by zavndw** [vedmak3/vedmak3.github.io#1]
Предлагаю max-width установить в 90%
Тогда и на экране удобнее строить схему и от разрешения особо не зависит

**Comment by vedmak3** [comment]
Да как вариант. Просто я ориентировался на формат А4. Чтобы печатать более менее можно было. Хотя на мобилке нормально смотрится.

**Comment by zavndw** [comment]
а на печать все ровно уходит не видимая область, я поэтому и растянул

**Comment by vedmak3** [comment]
Сделал 95 посмотрим как оценят. Спасибо
